services:
  nats:
    image: nats:latest
    container_name: eco-store-nats
    ports:
      - "4222:4222"

  postgres:
    image: postgres:16-alpine
    container_name: eco-store-product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_pass
    ports:
      - "5432:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

  checkout-db:
    image: postgres:16-alpine
    container_name: eco-store-checkout-db
    environment:
      POSTGRES_DB: checkout_db
      POSTGRES_USER: checkout_user
      POSTGRES_PASSWORD: checkout_pass
    ports:
      - "5433:5432"
    volumes:
      - checkout-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: eco-store-cart-redis
    ports:
      - "6379:6379"

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: eco-store-product-service
    environment:
      NATS_URL: nats://nats:4222
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/product_db
      SPRING_DATASOURCE_USERNAME: product_user
      SPRING_DATASOURCE_PASSWORD: product_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - nats
      - postgres
    ports:
      - "8081:8081"

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
    container_name: eco-store-cart-service
    environment:
      NATS_URL: nats://nats:4222
      SERVER_PORT: 8082
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - nats
      - redis
      - product-service
    ports:
      - "8082:8082"

  checkout-service:
    build:
      context: .
      dockerfile: checkout-service/Dockerfile
    container_name: eco-store-checkout-service
    environment:
      NATS_URL: nats://nats:4222
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:postgresql://checkout-db:5432/checkout_db
      SPRING_DATASOURCE_USERNAME: checkout_user
      SPRING_DATASOURCE_PASSWORD: checkout_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - nats
      - checkout-db
      - product-service
      - cart-service
    ports:
      - "8083:8083"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: eco-store-api-gateway
    environment:
      NATS_URL: nats://nats:4222
      SERVER_PORT: 8080
    depends_on:
      - nats
      - product-service
      - cart-service
      - checkout-service
    ports:
      - "8080:8080"

volumes:
  product-db-data:
  checkout-db-data:
