spring.application.name=users-service
server.port=8084

# Database (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/users_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:users_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:users_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET:65c77a90b452fc8d9b6cb6e7e12090ca2a5b144faaccc23cff0169734974a525}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
app.jwt.reset-expiration=${JWT_RESET_EXPIRATION:900000}

# NATS
nats.url=${NATS_URL:nats://localhost:4222}
nats.subject.auth.login=v1.auth.login
nats.subject.auth.register=v1.auth.register
nats.subject.auth.forgot-password=v1.auth.forgot-password
nats.subject.auth.reset-password=v1.auth.reset-password
nats.subject.user.create=v1.user.create
nats.subject.user.get=v1.user.get
nats.subject.user.update=v1.user.update

# Swagger / OpenAPI
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html