spring.application.name=api-gateway
server.port=8080

# Swagger / OpenAPI (SpringDoc)
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

nats.url=nats://localhost:4222
nats.request-timeout-ms=3000
nats.subject.product.create=v1.catalog.product.create
nats.subject.product.get=v1.catalog.product.get
nats.subject.product.list=v1.catalog.product.list
nats.subject.product.update=v1.catalog.product.update
nats.subject.product.delete=v1.catalog.product.delete
nats.subject.cart.add-product=v1.cart.add-product
nats.subject.cart.remove-product=v1.cart.remove-product
nats.subject.cart.get=v1.cart.get
nats.subject.cart.checkout=v1.cart.checkout
nats.subject.checkout.process=v1.checkout.process
nats.subject.checkout.confirm=v1.checkout.confirm
