spring.application.name=product-service
server.port=8081

# Database (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:product_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:product_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# NATS
nats.url=nats://localhost:4222
nats.subject.product.create=v1.catalog.product.create
nats.subject.product.get=v1.catalog.product.get
nats.subject.product.list=v1.catalog.product.list
nats.subject.product.update=v1.catalog.product.update
nats.subject.product.delete=v1.catalog.product.delete
