spring.application.name=cart-service
server.port=8082

# Redis
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# NATS
nats.url=${NATS_URL:nats://localhost:4222}
nats.subject.product.get=v1.catalog.product.get
nats.subject.cart.add-product=v1.cart.add-product
nats.subject.cart.remove-product=v1.cart.remove-product
nats.subject.cart.get=v1.cart.get
nats.subject.cart.checkout=v1.cart.checkout
nats.subject.cart.checkout-event=v1.cart.checkout.completed
